import { Link, useParams } from 'react-router-dom'
import { Alert, Box, Button, Chip, Paper, Typography } from '@mui/material'
import { ContentCopyRounded, QrCode2Rounded } from '@mui/icons-material'
import { StatusChip } from '@/components/ui/StatusChip'
import { useAuthStore } from '@/features/auth/auth.store'
import { EVENT_TYPE_LABELS } from '@/features/events/events.types'
import { useFarmerBatch } from '../batches.queries'

export function BatchDetailPage(){const {batchId}=useParams();const orgId=useAuthStore(s=>s.user?.organizationId)??1;const {data:b,isLoading}=useFarmerBatch(Number(batchId),orgId)
  if(isLoading)return <Typography>Đang tải…</Typography>;if(!b)return <Alert severity="warning">Không tìm thấy lô hàng. <Button component={Link} to="/batches">Quay lại</Button></Alert>
  return <Box sx={{display:'flex',flexDirection:'column',gap:3}}><Box sx={{display:'flex',justifyContent:'space-between',gap:2,flexWrap:'wrap'}}><Box><Typography color="primary" sx={{fontWeight:800}}>CHI TIẾT LÔ HÀNG</Typography><Typography variant="h4" sx={{fontWeight:900}}>{b.batchCode}</Typography><Typography color="text.secondary">{b.productName} • {b.producerOrganizationName}</Typography></Box><Box><Button component={Link} to="/batches">Quay lại danh sách</Button></Box></Box>
  <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'2fr 1fr'},gap:2}}><Paper sx={{p:3,border:'1px solid',borderColor:'divider',borderRadius:3}}><Typography variant="h6" sx={{fontWeight:800,mb:2}}>Thông tin sản xuất</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2}}>{[['Sản phẩm',b.productName],['Khối lượng',`${b.weight} ${b.unit}`],['Ngày thu hoạch',new Date(b.harvestDate).toLocaleDateString('vi-VN')],['Trạng thái',b.status],['Nông trại',b.producerOrganizationName],['Ngày tạo',new Date(b.createdAt).toLocaleString('vi-VN')]].map(([k,v])=><Box key={k}><Typography variant="caption" color="text.secondary">{k}</Typography>{k==='Trạng thái'?<Box><StatusChip status={v || ''}/></Box>:<Typography sx={{fontWeight:700}}>{v}</Typography>}</Box>)}</Box></Paper>
  <Paper sx={{p:3,border:'1px solid',borderColor:'divider',borderRadius:3,textAlign:'center'}}><QrCode2Rounded sx={{fontSize:110,color:'primary.main'}}/><Typography sx={{fontWeight:800}}>Mã truy xuất</Typography><Typography variant="body2" color="text.secondary" sx={{wordBreak:'break-all'}}>{b.qrCode}</Typography><Button size="small" startIcon={<ContentCopyRounded/>} onClick={()=>void navigator.clipboard.writeText(`${location.origin}${b.qrCode}`)} sx={{mt:1}}>Sao chép liên kết</Button></Paper></Box>
  <Paper sx={{p:3,border:'1px solid',borderColor:'divider',borderRadius:3}}><Typography variant="h6" sx={{fontWeight:800}}>Lịch sử bất biến</Typography><Typography variant="body2" color="text.secondary" sx={{mb:2}}>Các sự kiện chỉ được thêm mới, không thể sửa hoặc xóa.</Typography>{b.events.map(e=><Box key={e.eventId} sx={{borderLeft:'3px solid',borderColor:'primary.main',pl:2,py:1,mb:2}}><Box sx={{display:'flex',gap:1,alignItems:'center'}}><Chip label={EVENT_TYPE_LABELS[e.eventType] ?? e.eventType} color="success" size="small"/><Typography variant="body2">{new Date(e.eventTime).toLocaleString('vi-VN')}</Typography></Box><Typography sx={{mt:1}}>{e.location||'Không có địa điểm'}</Typography>{e.additionalData&&<Typography variant="body2" color="text.secondary">{e.additionalData}</Typography>}<Typography variant="caption" color="text.secondary" sx={{display:'block',wordBreak:'break-all'}}>Hash: {e.currentHash}</Typography></Box>)}</Paper></Box>}
