import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Alert, Box, Button, Chip, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { AddRounded, OpenInNewRounded } from '@mui/icons-material'
import { certificatesApi, type Certificate } from '../certificates.api'

export function CertificatesPage() {
  const client = useQueryClient(); const [batchId, setBatchId] = useState(''); const [type, setType] = useState('VietGAP'); const [fileUrl, setFileUrl] = useState(''); const parsed = Number(batchId)
  const query = useQuery({ queryKey: ['certificates', parsed], queryFn: () => certificatesApi.getByBatch(parsed), enabled: parsed > 0 })
  const create = useMutation({ mutationFn: () => certificatesApi.create(parsed, { certificateType: type, fileUrl }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['certificates', parsed] }); setFileUrl('') } })
  return <Box><Typography variant="h4" sx={{ fontWeight: 900 }}>Chứng nhận tiêu chuẩn</Typography><Typography color="text.secondary" sx={{ mt: 0.5, mb: 3 }}>Cấp và tra cứu chứng nhận VietGAP, GlobalGAP theo lô hàng.</Typography><Paper variant="outlined" sx={{ p: 2, mb: 2, borderRadius: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField label="ID lô hàng" type="number" value={batchId} onChange={(event) => setBatchId(event.target.value)} /><TextField label="Loại chứng nhận" value={type} onChange={(event) => setType(event.target.value)} /><TextField label="URL file chứng nhận" value={fileUrl} onChange={(event) => setFileUrl(event.target.value)} sx={{ flex: 1 }} /><Button variant="contained" startIcon={<AddRounded />} disabled={!parsed || !type || !fileUrl || create.isPending} onClick={() => create.mutate()} sx={{ textTransform: 'none', whiteSpace: 'nowrap' }}>Cấp chứng nhận</Button></Stack></Paper>{query.isError || create.isError ? <Alert severity="error" sx={{ mb: 2 }}>Không thể xử lý chứng nhận.</Alert> : null}<TableContainer component={Paper} variant="outlined" sx={{ borderRadius: 3 }}><Table><TableHead><TableRow sx={{ bgcolor: 'grey.50' }}><TableCell>Mã</TableCell><TableCell>Loại</TableCell><TableCell>Ngày cấp</TableCell><TableCell>File</TableCell></TableRow></TableHead><TableBody>{(query.data ?? []).map((certificate: Certificate) => <TableRow key={certificate.id}><TableCell>#{certificate.id}</TableCell><TableCell><Chip label={certificate.certificateType ?? '-'} color="success" size="small" /></TableCell><TableCell>{certificate.issuedDate ? new Date(certificate.issuedDate).toLocaleDateString('vi-VN') : '-'}</TableCell><TableCell>{certificate.fileUrl ? <Button href={certificate.fileUrl} target="_blank" size="small" endIcon={<OpenInNewRounded />} sx={{ textTransform: 'none' }}>Mở file</Button> : '-'}</TableCell></TableRow>)}{parsed > 0 && !query.isLoading && !query.data?.length ? <TableRow><TableCell colSpan={4} align="center" sx={{ py: 5, color: 'text.secondary' }}>Chưa có chứng nhận cho lô này.</TableCell></TableRow> : null}</TableBody></Table></TableContainer></Box>
}