import type {
  CanhBaoThuHoi,
  ChungNhan,
  DonVi,
  KiemDinh,
  LoHang,
  NguoiDung,
  SanPham,
  SuKien,
  ThongBaoThuHoi,
  VaiTro,
} from './admin.types'

export const mockVaiTros: VaiTro[] = [
  {
    maVaiTro: 1,
    tenVaiTro: 'Admin',
    moTa: 'Quản trị toàn bộ hệ thống',
  },
  {
    maVaiTro: 2,
    tenVaiTro: 'Farmer',
    moTa: 'Đơn vị sản xuất / nông hộ',
  },
  {
    maVaiTro: 3,
    tenVaiTro: 'Processor',
    moTa: 'Đơn vị sơ chế, chế biến',
  },
  {
    maVaiTro: 4,
    tenVaiTro: 'Distributor',
    moTa: 'Đơn vị vận chuyển, phân phối',
  },
  {
    maVaiTro: 5,
    tenVaiTro: 'Retailer',
    moTa: 'Đơn vị bán lẻ',
  },
  {
    maVaiTro: 6,
    tenVaiTro: 'Inspector',
    moTa: 'Đơn vị kiểm định chất lượng',
  },
]

export const mockDonVis: DonVi[] = [
  {
    maDonVi: 1,
    tenDonVi: 'HTX Rau sạch Đà Lạt',
    loaiDonVi: 'Farmer',
    diaChi: 'Đà Lạt, Lâm Đồng',
    soDienThoai: '0901234567',
    maSoThue: '5801492101',
    trangThai: 'Active',
  },
  {
    maDonVi: 2,
    tenDonVi: 'Nhà máy Chế biến Nông sản Việt',
    loaiDonVi: 'Processor',
    diaChi: 'Long An',
    soDienThoai: '0902345678',
    maSoThue: '1102034567',
    trangThai: 'Active',
  },
  {
    maDonVi: 3,
    tenDonVi: 'Công ty Vận tải Chuỗi Xanh',
    loaiDonVi: 'Distributor',
    diaChi: 'TP. Hồ Chí Minh',
    soDienThoai: '0903456789',
    maSoThue: '0317426185',
    trangThai: 'Active',
  },
  {
    maDonVi: 4,
    tenDonVi: 'Siêu thị GreenMart',
    loaiDonVi: 'Retailer',
    diaChi: 'Hà Nội',
    soDienThoai: '0904567890',
    maSoThue: '0109854321',
    trangThai: 'Active',
  },
  {
    maDonVi: 5,
    tenDonVi: 'Trung tâm Kiểm định Nông nghiệp',
    loaiDonVi: 'Inspector',
    diaChi: 'Hà Nội',
    soDienThoai: '0905678901',
    maSoThue: '0101239876',
    trangThai: 'Active',
  },
]

export const mockNguoiDungs: NguoiDung[] = [
  {
    maNguoiDung: 1,
    maVaiTro: 1,
    maDonVi: null,
    tenDangNhap: 'admin',
    email: 'admin@gmail.com',
    hoTen: 'Nguyễn Văn A',
    ngayTao: '2026-08-01',
    trangThai: 'Active',
  },
  {
    maNguoiDung: 2,
    maVaiTro: 2,
    maDonVi: 1,
    tenDangNhap: 'farmer.hung',
    email: 'hung@dalatfarm.vn',
    hoTen: 'Trần Văn Hùng',
    ngayTao: '2026-08-02',
    trangThai: 'Active',
  },
  {
    maNguoiDung: 3,
    maVaiTro: 3,
    maDonVi: 2,
    tenDangNhap: 'processor.ha',
    email: 'ha@processor.vn',
    hoTen: 'Lê Thu Hà',
    ngayTao: '2026-08-02',
    trangThai: 'Active',
  },
  {
    maNguoiDung: 4,
    maVaiTro: 4,
    maDonVi: 3,
    tenDangNhap: 'shipper.nam',
    email: 'nam@chuoixanh.vn',
    hoTen: 'Phạm Quốc Nam',
    ngayTao: '2026-08-03',
    trangThai: 'Active',
  },
  {
    maNguoiDung: 5,
    maVaiTro: 6,
    maDonVi: 5,
    tenDangNhap: 'inspector.lan',
    email: 'lan@kiemdinhnn.vn',
    hoTen: 'Vũ Thị Lan',
    ngayTao: '2026-08-04',
    trangThai: 'Inactive',
  },
]

export const mockSanPhams: SanPham[] = [
  {
    maSanPham: 1,
    tenSanPham: 'Cà chua Beef',
    donViTinh: 'kg',
    moTa: 'Cà chua nhà kính đạt VietGAP',
  },
  {
    maSanPham: 2,
    tenSanPham: 'Xà lách Romaine',
    donViTinh: 'kg',
    moTa: 'Xà lách thủy canh đóng gói tại nguồn',
  },
  {
    maSanPham: 3,
    tenSanPham: 'Khoai lang mật',
    donViTinh: 'thùng',
    moTa: 'Khoai lang mật loại 1',
  },
  {
    maSanPham: 4,
    tenSanPham: 'Dâu tây hữu cơ',
    donViTinh: 'hộp',
    moTa: 'Dâu tây hữu cơ Đà Lạt',
  },
]

export const mockLoHangs: LoHang[] = [
  {
    maLoHang: 1,
    maSanPham: 1,
    maDonViSanXuat: 1,
    maLoHangCha: null,
    maQR: 'QR-LH-0001',
    ngayThuHoach: '2026-08-01',
    khoiLuong: 1250,
    trangThai: 'Distributed',
    ngayTao: '2026-08-01T07:00:00',
  },
  {
    maLoHang: 2,
    maSanPham: 2,
    maDonViSanXuat: 1,
    maLoHangCha: null,
    maQR: 'QR-LH-0002',
    ngayThuHoach: '2026-08-02',
    khoiLuong: 780,
    trangThai: 'InTransit',
    ngayTao: '2026-08-02T07:30:00',
  },
  {
    maLoHang: 3,
    maSanPham: 3,
    maDonViSanXuat: 1,
    maLoHangCha: null,
    maQR: 'QR-LH-0003',
    ngayThuHoach: '2026-08-03',
    khoiLuong: 2100,
    trangThai: 'Processed',
    ngayTao: '2026-08-03T08:00:00',
  },
  {
    maLoHang: 4,
    maSanPham: 4,
    maDonViSanXuat: 1,
    maLoHangCha: null,
    maQR: 'QR-LH-0004',
    ngayThuHoach: '2026-08-04',
    khoiLuong: 460,
    trangThai: 'Created',
    ngayTao: '2026-08-04T06:40:00',
  },
  {
    maLoHang: 5,
    maSanPham: 1,
    maDonViSanXuat: 1,
    maLoHangCha: 1,
    maQR: 'QR-LH-0001-A',
    ngayThuHoach: '2026-08-01',
    khoiLuong: 320,
    trangThai: 'Recalled',
    ngayTao: '2026-08-02T10:00:00',
  },
]

export const mockSuKiens: SuKien[] = [
  {
    maSuKien: 1,
    maLoHang: 1,
    maDonViThucHien: 1,
    maNguoiThucHien: 2,
    maSuKienTruoc: null,
    loaiSuKien: 'Harvest',
    thoiGian: '2026-08-01T06:30:00',
    viTri: 'Đà Lạt, Lâm Đồng',
    duLieuBoSung: '{"temperature":18,"humidity":78}',
    maHash: '7af9c43b54e3110d81251e01775f163f',
    maHashTruoc: null,
  },
  {
    maSuKien: 2,
    maLoHang: 1,
    maDonViThucHien: 2,
    maNguoiThucHien: 3,
    maSuKienTruoc: 1,
    loaiSuKien: 'Process',
    thoiGian: '2026-08-02T09:40:00',
    viTri: 'Long An',
    duLieuBoSung: '{"temperature":12,"line":"A02"}',
    maHash: 'e184d42e4d391d372e0cdde776f5d60e',
    maHashTruoc: '7af9c43b54e3110d81251e01775f163f',
  },
  {
    maSuKien: 3,
    maLoHang: 2,
    maDonViThucHien: 3,
    maNguoiThucHien: 4,
    maSuKienTruoc: null,
    loaiSuKien: 'Transport',
    thoiGian: '2026-08-03T05:15:00',
    viTri: 'Đồng Nai',
    duLieuBoSung: '{"vehicle":"51D-123.45","temperature":7}',
    maHash: 'f47e09c97478d880585348947a48367b2',
    maHashTruoc: null,
  },
]

export const mockKiemDinhs: KiemDinh[] = [
  {
    maKiemDinh: 1,
    maLoHang: 1,
    maDonViKiemDinh: 5,
    ketQua: 'Passed',
    ngayKiemDinh: '2026-08-02',
    ghiChu: 'Đạt tiêu chuẩn an toàn thực phẩm',
  },
  {
    maKiemDinh: 2,
    maLoHang: 2,
    maDonViKiemDinh: 5,
    ketQua: 'Passed',
    ngayKiemDinh: '2026-08-03',
    ghiChu: 'Không phát hiện chất cấm',
  },
  {
    maKiemDinh: 3,
    maLoHang: 5,
    maDonViKiemDinh: 5,
    ketQua: 'Failed',
    ngayKiemDinh: '2026-08-05',
    ghiChu: 'Nhiệt độ bảo quản không đạt',
  },
]

export const mockChungNhans: ChungNhan[] = [
  {
    maChungNhan: 1,
    maLoHang: 1,
    maKiemDinh: 1,
    loaiChungNhan: 'VietGAP',
    fileChungNhanUrl: '#',
    donViCap: 'Sở NN&PTNT Lâm Đồng',
    ngayCap: '2026-08-02',
    ngayHetHan: '2027-08-02',
  },
  {
    maChungNhan: 2,
    maLoHang: 2,
    maKiemDinh: 2,
    loaiChungNhan: 'Organic',
    fileChungNhanUrl: '#',
    donViCap: 'Chứng nhận Hữu cơ Việt Nam',
    ngayCap: '2026-08-03',
    ngayHetHan: '2027-08-03',
  },
  {
    maChungNhan: 3,
    maLoHang: 3,
    maKiemDinh: null,
    loaiChungNhan: 'HACCP',
    fileChungNhanUrl: '#',
    donViCap: 'Bureau Veritas Việt Nam',
    ngayCap: '2026-08-04',
    ngayHetHan: '2028-08-04',
  },
]

export const mockCanhBaoThuHois: CanhBaoThuHoi[] = [
  {
    maCanhBao: 1,
    maLoHang: 5,
    maNguoiTao: 5,
    lyDo: 'Nhiệt độ bảo quản vượt ngưỡng cho phép',
    mucDoNghiemTrong: 'Critical',
    thoiGianTao: '2026-08-05T16:20:00',
    trangThai: 'Active',
  },
  {
    maCanhBao: 2,
    maLoHang: 3,
    maNguoiTao: 1,
    lyDo: 'Sai thông tin khối lượng trên nhãn',
    mucDoNghiemTrong: 'Medium',
    thoiGianTao: '2026-08-04T10:30:00',
    trangThai: 'Resolved',
  },
]

export const mockThongBaoThuHois: ThongBaoThuHoi[] = [
  {
    maThongBao: 1,
    maCanhBao: 1,
    maDonVi: 2,
    thoiGianGui: '2026-08-05T16:25:00',
    trangThaiXacNhan: 'Acknowledged',
    ghiChuXuLy: 'Đã khóa lô hàng trong kho',
  },
  {
    maThongBao: 2,
    maCanhBao: 1,
    maDonVi: 3,
    thoiGianGui: '2026-08-05T16:25:00',
    trangThaiXacNhan: 'Processed',
    ghiChuXuLy: 'Đã cung cấp dữ liệu cảm biến',
  },
  {
    maThongBao: 3,
    maCanhBao: 1,
    maDonVi: 4,
    thoiGianGui: '2026-08-05T16:26:00',
    trangThaiXacNhan: 'Pending',
    ghiChuXuLy: 'Chưa phản hồi',
  },
]