import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Box, Button, Chip, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { AddRounded, CheckCircleRounded, SearchRounded, VerifiedRounded } from '@mui/icons-material'
import { batchesApi } from '@/features/batches/batches.api'
import type { BatchEvent, EventType } from '../events.types'

const eventTypes: EventType[] = ['HARVEST', 'PROCESS', 'PACKAGE', 'TRANSPORT', 'DISTRIBUTE', 'RETAIL']

export function EventsPage() {
  const navigate = useNavigate()
  const [batchId, setBatchId] = useState('')
  const [eventType, setEventType] = useState('')
  const parsedBatchId = Number(batchId)
  const query = useQuery({ queryKey: ['batch-events', parsedBatchId], queryFn: () => batchesApi.getBatchEvents(parsedBatchId), enabled: Number.isInteger(parsedBatchId) && parsedBatchId > 0 })
  const verify = useQuery({ queryKey: ['batch-integrity', parsedBatchId], queryFn: () => batchesApi.verifyIntegrity(parsedBatchId), enabled: false })
  const rows = (query.data ?? []).filter((event: BatchEvent) => !eventType || event.eventType === eventType)

  return <Box><Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, mb: 3, alignItems: { xs: 'flex-start', md: 'center' }, flexDirection: { xs: 'column', md: 'row' } }}><Box><Typography variant="h4" sx={{ fontWeight: 900 }}>Chuỗi sự kiện</Typography><Typography color="text.secondary" sx={{ mt: 0.5 }}>Nhật ký append-only của từng lô hàng và hash chain SHA-256.</Typography></Box><Button variant="contained" startIcon={<AddRounded />} onClick={() => navigate('/events/new')} sx={{ textTransform: 'none', borderRadius: 2, fontWeight: 800 }}>Ghi nhận sự kiện</Button></Box><Paper variant="outlined" sx={{ p: 2, mb: 2, borderRadius: 3, display: 'flex', gap: 2, flexWrap: 'wrap' }}><TextField size="small" label="ID lô hàng" value={batchId} onChange={(event) => setBatchId(event.target.value)} sx={{ flex: 1, minWidth: 220 }} slotProps={{ input: { startAdornment: <SearchRounded sx={{ mr: 1, color: 'text.secondary' }} /> } }} /><TextField select size="small" label="Loại sự kiện" value={eventType} onChange={(event) => setEventType(event.target.value)} sx={{ minWidth: 200 }}><MenuItem value="">Tất cả</MenuItem>{eventTypes.map((type) => <MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField><Button variant="outlined" startIcon={<VerifiedRounded />} disabled={!batchId || verify.isFetching} onClick={() => void verify.refetch()} sx={{ textTransform: 'none' }}>Kiểm tra toàn vẹn</Button></Paper>{verify.data && <Alert severity="success" icon={<CheckCircleRounded />} sx={{ mb: 2 }}>Đã hoàn tất kiểm tra hash chain cho lô #{batchId}.</Alert>}{query.isError && <Alert severity="error" sx={{ mb: 2 }}>Không thể tải sự kiện của lô hàng.</Alert>}<TableContainer component={Paper} variant="outlined" sx={{ borderRadius: 3 }}><Table><TableHead><TableRow sx={{ bgcolor: 'grey.50' }}><TableCell>Loại</TableCell><TableCell>Thời gian</TableCell><TableCell>Địa điểm</TableCell><TableCell>Dữ liệu</TableCell><TableCell>Current hash</TableCell></TableRow></TableHead><TableBody>{rows.map((event: BatchEvent) => <TableRow key={event.eventId} hover><TableCell><Chip label={event.eventType} color={event.eventType === 'HARVEST' ? 'success' : 'primary'} size="small" /></TableCell><TableCell>{new Date(event.eventTime).toLocaleString('vi-VN')}</TableCell><TableCell>{event.location ?? '-'}</TableCell><TableCell>{event.additionalData ?? '-'}</TableCell><TableCell sx={{ maxWidth: 220, fontFamily: 'monospace', fontSize: 11, wordBreak: 'break-all' }}>{event.currentHash}</TableCell></TableRow>)}{!query.isLoading && rows.length === 0 && <TableRow><TableCell colSpan={5} align="center" sx={{ py: 6, color: 'text.secondary' }}>{batchId ? 'Chưa có sự kiện phù hợp.' : 'Nhập ID lô để xem chuỗi sự kiện.'}</TableCell></TableRow>}</TableBody></Table></TableContainer></Box>
}