import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Box, Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material'
import { ArrowBackRounded, SaveRounded, WarningAmberRounded } from '@mui/icons-material'
import { recallsApi } from '../recalls.api'

export function CreateRecallPage() {
  const navigate = useNavigate(); const client = useQueryClient(); const [batchId, setBatchId] = useState(''); const [reason, setReason] = useState(''); const [severity, setSeverity] = useState('HIGH')
  const mutation = useMutation({ mutationFn: () => recallsApi.create({ batchId: Number(batchId), reason: reason.trim(), severity }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['recalls'] }); navigate('/admin/recalls') } })
  return <Box sx={{ maxWidth: 720, mx: 'auto' }}><Button startIcon={<ArrowBackRounded />} onClick={() => navigate('/admin/recalls')} sx={{ textTransform: 'none', mb: 2 }}>Quay lại</Button><Paper variant="outlined" sx={{ p: { xs: 2, sm: 4 }, borderRadius: 3 }}><Stack direction="row" gap={1} alignItems="center"><WarningAmberRounded color="error" /><Typography variant="h5" sx={{ fontWeight: 900 }}>Phát hành thu hồi</Typography></Stack><Typography color="text.secondary" sx={{ mt: 1, mb: 3 }}>Lệnh thu hồi sẽ lan truyền tới các tổ chức liên quan.</Typography>{mutation.isError && <Alert severity="error" sx={{ mb: 2 }}>Không thể tạo lệnh thu hồi.</Alert>}<Stack spacing={2}><TextField label="ID lô hàng" type="number" required value={batchId} onChange={(event) => setBatchId(event.target.value)} /><TextField select label="Mức độ" value={severity} onChange={(event) => setSeverity(event.target.value)}><MenuItem value="LOW">LOW - Thấp</MenuItem><MenuItem value="MEDIUM">MEDIUM - Trung bình</MenuItem><MenuItem value="HIGH">HIGH - Cao</MenuItem><MenuItem value="CRITICAL">CRITICAL - Khẩn cấp</MenuItem></TextField><TextField label="Lý do thu hồi" multiline minRows={4} required value={reason} onChange={(event) => setReason(event.target.value)} /><Button variant="contained" color="error" startIcon={<SaveRounded />} disabled={!batchId || !reason.trim() || mutation.isPending} onClick={() => mutation.mutate()} sx={{ alignSelf: 'flex-end', textTransform: 'none', fontWeight: 800 }}>Xác nhận thu hồi</Button></Stack></Paper></Box>
}