import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, Box, Button, Chip, Paper, Stack, Typography } from '@mui/material'
import { CheckRounded, WarningAmberRounded } from '@mui/icons-material'
import { useAuthStore } from '@/features/auth/auth.store'
import { recallNotificationsApi, type RecallNotification } from '../recall-notifications.api'

export function RecallNotificationsPage() {
  const user = useAuthStore((state) => state.user); const client = useQueryClient(); const organizationId = user?.organizationId ?? 0
  const query = useQuery({ queryKey: ['recall-notifications', organizationId], queryFn: () => recallNotificationsApi.getForOrganization(organizationId), enabled: organizationId > 0 })
  const acknowledge = useMutation({ mutationFn: ({ id, notes }: { id: number; notes?: string }) => recallNotificationsApi.acknowledge(id, notes), onSuccess: () => void client.invalidateQueries({ queryKey: ['recall-notifications', organizationId] }) })
  return <Box><Typography variant="h4" sx={{ fontWeight: 900 }}>Thông báo thu hồi</Typography><Typography color="text.secondary" sx={{ mt: 0.5, mb: 3 }}>Các cảnh báo liên quan đến tổ chức của bạn.</Typography>{organizationId === 0 && <Alert severity="info">Tài khoản chưa được gán tổ chức.</Alert>}{query.isError && <Alert severity="error">Không thể tải thông báo thu hồi.</Alert>}<Stack spacing={2}>{(query.data ?? []).map((item: RecallNotification) => <Paper key={item.id} variant="outlined" sx={{ p: 2.5, borderRadius: 3 }}><Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, flexDirection: { xs: 'column', sm: 'row' } }}><Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}><WarningAmberRounded color="error" /><Typography sx={{ fontWeight: 900 }}>Cảnh báo thu hồi #{item.recallId ?? item.id}</Typography><Chip size="small" label={item.severity ?? item.status ?? 'PENDING'} color="error" /></Box><Typography color="text.secondary" sx={{ mt: 1 }}>{item.message ?? item.reason ?? 'Có một lệnh thu hồi liên quan đến tổ chức.'}</Typography></Box><Button variant="outlined" startIcon={<CheckRounded />} disabled={item.status === 'ACKNOWLEDGED' || acknowledge.isPending} onClick={() => acknowledge.mutate({ id: item.id })} sx={{ textTransform: 'none', whiteSpace: 'nowrap' }}>{item.status === 'ACKNOWLEDGED' ? 'Đã xác nhận' : 'Xác nhận đã nhận'}</Button></Box></Paper>)}{organizationId > 0 && !query.isLoading && !query.data?.length && <Paper variant="outlined" sx={{ p: 5, textAlign: 'center', color: 'text.secondary' }}>Không có thông báo thu hồi.</Paper>}</Stack></Box>
}